# Generated by Django 5.2.5 on 2025-09-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_item_item_uuid_receipt_receipt_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='tax',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
