# Generated by Django 5.2.5 on 2025-09-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_receipt_tax_receipt_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='subtotal',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
