# Generated by Django 5.2.5 on 2025-09-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_receipt_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='taxpercent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
