# Generated by Django 5.2.5 on 2025-09-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_receipt_taxpercent'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
