# Generated by Django 5.2.5 on 2025-09-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_item_last_updated_receipt_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='num_receipts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receipt',
            name='num_items',
            field=models.IntegerField(default=0),
        ),
    ]
