# Generated by Django 5.2.5 on 2025-10-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0007_customuser_num_receipts_receipt_num_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='address',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
