# Generated by Django 5.2.5 on 2025-10-16 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0008_receipt_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='stores_checked',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date_purchased',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
