# Generated by Django 5.2.5 on 2025-10-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0009_item_item_number_receipt_receipt_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stores_checked',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
